# Usa l'immagine base ZED SDK 5.0 con CUDA 12.8 su Ubuntu 22.04
FROM stereolabs/zed:5.1-gl-devel-cuda12.8-ubuntu22.04 

# Definisci la distribuzione ROS 2
ENV ROS_DISTRO=humble
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Installa ROS 2 Humble + dipendenze
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata curl wget gnupg lsb-release && \
    \
    # Aggiunge il repository ROS 2
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc \
    | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
    http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
    > /etc/apt/sources.list.d/ros2.list && \
    \
    # Installa ROS 2 + dipendenze build
    apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ros-$ROS_DISTRO-desktop-full \
        ros-$ROS_DISTRO-vision-msgs \
        ros-$ROS_DISTRO-ament-cmake-auto \
        ros-$ROS_DISTRO-navigation2 \
        ros-$ROS_DISTRO-nav2-bringup \
        ros-$ROS_DISTRO-nav2-rviz-plugins \
        ros-$ROS_DISTRO-slam-toolbox \
        build-essential \
        python3-rosdep \
        python3-pip \
        cmake \
        python3-colcon-common-extensions \
        usbutils \
        libusb-1.0-0-dev \
        git \
        --no-install-recommends && \
    \
    # Pulisce la cache APT
    rm -rf /var/lib/apt/lists/*

RUN rosdep init && \
    rosdep update

RUN pip3 install ultralytics && \
    pip3 install "numpy<2.0"

WORKDIR /root/ros_workspace